spring:
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5433/Tasks
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
